services:
  db:
    env_file:
      - .env.example
    container_name: example_postgres
    image: postgres:16
    restart: always
    volumes:
      - example_postgres_data:/var/lib/postgresql/data
    #      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - "5444:5432"

volumes:
  example_postgres_data:
    driver: local  # Драйвер по умолчанию (локальное хранилище)
