services:
  rabbitmq:
    image: rabbitmq:3-management  # management - доп плагин для UI
    ports:
      - "5672:5672"  # default
      - "15672:15672"  # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped  # если контейнер работал до перезагрузки, он будет перезапущен после перезапуска системы


volumes:
  rabbitmq_data:
    driver: local  # Драйвер по умолчанию (локальное хранилище)
