services:
  postgres:
    container_name: rfid_postgres
    env_file:
      - .env
    image: postgres
    restart: always
    volumes:
      - rfid_postgres_data:/var/lib/postgresql/data
    #      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - "6382:5432"


volumes:
  postgres_data:
    driver: local
